name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Step 1: Lint and format check
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Prettier check
        run: npx prettier --check .
      - name: ESLint check
        run: npx eslint . --ext .ts,.tsx

  # Step 2: Build, type-check, and test
  build-and-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Type-check
        run: npm run type-check
      - name: Run tests
        run: npm test
      - name: Next.js build
        run: npm run build

  # Step 4: Deploy to Railway
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --yes
